### ISSUE TITLE
No such file or directory => os.makedirs(outdir)

### ISSUE THREAD

**Issue by nick-youngblut** [smirarab/sepp#104]
```
$ run_tipp_tool.py -g markers-v1/pyrg \
>                  -a profile \
>                  -o output_profile \
>                  -p markers-v1_pyrg \
>                  -i output_classification.txt \
>                  -t 0.95
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/bin/run_tipp_tool.py", line 4, in <module>
    __import__('pkg_resources').run_script('sepp==4.3.21', 'run_tipp_tool.py')
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/lib/python3.7/site-packages/sepp-4.3.21-py3.7.egg/EGG-INFO/scripts/run_tipp_tool.py", line 73, in <module>
    main()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/lib/python3.7/site-packages/sepp-4.3.21-py3.7.egg/EGG-INFO/scripts/run_tipp_tool.py", line 69, in main
    args.threshold)
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/lib/python3.7/site-packages/sepp-4.3.21-py3.7.egg/EGG-INFO/scripts/run_tipp_tool.py", line 61, in profile
    gene_classification, "%s/%s.classification" % (output, prefix))
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/tipp2/lib/python3.7/site-packages/sepp-4.3.21-py3.7.egg/sepp/metagenomics.py", line 337, in write_classification
    class_out = open(output, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'output_profile/markers-v1_pyrg.classification'
```

Adding a simple `os.makedirs(outdir)` will remove the need for creating the output directory path prior to running tipp

**Comment by ekmolloy** [comment]
We have implemented this feature request that `run_tipp_tool.py` creates the output directory for the user in the tipp2 branch. This change makes it possible for files to be overwritten, so we have added a warning.
