### ISSUE TITLE
UPP cannot locate Dendropy

### ISSUE THREAD

**Issue by aravenscraft** [smirarab/sepp#127]
I am trying to run UPP, but I get the error "The 'dendropy>=4.0.0' distribution was not found and is required by sepp." But Dendropy is installed. When I run _python3 -m pip install -U dendropy_, I get:

"Requirement already satisfied: dendropy in /usr/local/lib/python3.9/site-packages (4.6.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from dendropy) (54.1.2)"

How do I tell SEPP/UPP where to find my copy of Dendropy?

Full output below.

biol-128379:sepp ravenscrafta$ run_upp.py -h
Traceback (most recent call last):
  File "/usr/local/bin/run_upp.py", line 4, in <module>
    __import__('pkg_resources').run_script('sepp==4.5.2', 'run_upp.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dendropy>=4.0.0' distribution was not found and is required by sepp

**Comment by aravenscraft** [comment]
I think I found a workaround. I created a conda environment into which I re-installed SEPP and PASTA. It appears that SEPP can now find DendroPy, but I'm getting a different error which I'll post separately.
