### ISSUE TITLE
Python3.10 issue: ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by WWz33** [smirarab/sepp#130]
Traceback (most recent call last):
  File "/usr/local/bin/run_sepp.py", line 4, in <module>
    __import__('pkg_resources').run_script('sepp==4.5.1', 'run_sepp.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.10/dist-packages/sepp-4.5.1-py3.10.egg/EGG-INFO/scripts/run_sepp.py", line 3, in <module>
    from sepp.exhaustive import ExhaustiveAlgorithm
  File "/usr/local/lib/python3.10/dist-packages/sepp-4.5.1-py3.10.egg/sepp/exhaustive.py", line 6, in <module>
    from sepp.algorithm import AbstractAlgorithm
  File "/usr/local/lib/python3.10/dist-packages/sepp-4.5.1-py3.10.egg/sepp/algorithm.py", line 11, in <module>
    from sepp.alignment import MutableAlignment
  File "/usr/local/lib/python3.10/dist-packages/sepp-4.5.1-py3.10.egg/sepp/alignment.py", line 29, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**I think it's caused by this problem**
[https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections](url)

**Comment by NickShanyt** [comment]
I encounter this problem also.
fix:
vim yourPath/python3.11/site-packages/sepp-4.5.1-py3.11.egg/sepp/alignment.py

`from collections import Mapping`
to

`from collections.abc import Mapping`

**Comment by sjanssen2** [comment]
This should be fixed by https://github.com/smirarab/sepp/blob/c276adf34040cd2cb4095a965c2ae362e6bab228/sepp/alignment.py#L29-L32 Therefore, I think this issue can be closed @smirarab
