### ISSUE TITLE
run_tipp.py error: AttributeError: 'Namespace' object has no attribute 'exhaustive'

### ISSUE THREAD

**Issue by fbreitwieser** [smirarab/sepp#15]
Hello,
Thanks for this software. I just tried installing and running `run_tipp.py` for the first time but it produced the error below.

```
$ python --version
Python 2.7.5

$ run_tipp.py --version
[10:44:20] config.py (line 250):  WARNING: Main configuration file was not found at: /home/fbreitwieser/.sepp/tipp.config
Proceeding without the main configuration...
run_tipp.py 2.0

$ run_tipp.py 
[10:42:22] config.py (line 250):  WARNING: Main configuration file was not found at: /home/fbreitwieser/.sepp/tipp.config
Proceeding without the main configuration...
Traceback (most recent call last):
  File "/home/fbreitwieser/.local/bin/run_tipp.py", line 5, in <module>
    pkg_resources.run_script('sepp==3.1', 'run_tipp.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 487, in run_script
    if name is None:
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1337, in run_script
    
  File "/home/fbreitwieser/.local/lib/python2.7/site-packages/sepp-3.1-py2.7.egg/EGG-INFO/scripts/run_tipp.py", line 25, in <module>
    main()
  File "/home/fbreitwieser/.local/lib/python2.7/site-packages/sepp-3.1-py2.7.egg/sepp/exhaustive_tipp.py", line 500, in main
    TIPPExhaustiveAlgorithm().run()
  File "/home/fbreitwieser/.local/lib/python2.7/site-packages/sepp-3.1-py2.7.egg/sepp/exhaustive_tipp.py", line 283, in __init__
    ExhaustiveAlgorithm.__init__(self)    
  File "/home/fbreitwieser/.local/lib/python2.7/site-packages/sepp-3.1-py2.7.egg/sepp/exhaustive.py", line 193, in __init__
    self.strategy = options().exhaustive.strategy
AttributeError: 'Namespace' object has no attribute 'exhaustive'
```

Best,
Florian

**Comment by namphuon** [comment]
Hi Florian,

The configuration file not found might suggest that the software needs to be re-installed.  The installation process should create that file.

To quickly verify, the first step is to install SEPP -
- python setup.py install
- python setup.py config

And then set up TIPP
- python setup.py tipp

Can you run those commands and see if the configuration file exist?  If not, something else is going on.

Thanks!

Regards,
Nam

**Comment by fbreitwieser** [comment]
Hi Nam,
Thank you, that solves it! I just did the install command, and not the further ones. 
Thanks,
Florian

**Comment by namphuon** [comment]
Glad that helped.  I just wanted to point out that the TIPP readme (https://github.com/smirarab/sepp/blob/master/README.TIPP.md) has more detailed instructions on setting up TIPP.  You shouldn't run the 

setup.py tipp

command until you set the blastn executable location and the path to the reference package.  If you don't do these two things before running the command, TIPP will have problems finding the correct paths.
